apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongodb-article
    #namespace: my-app
    labels:
        app: mongodb-article
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mongodb-article
    template:
        metadata:
            labels:
                app: mongodb-article
        spec:
            containers:
            - name: mongodb-article
              image: mongo
              ports:
              - containerPort: 27017
              #env:
              #- name: MONGO_INITDB_ROOT_USERNAME
                #valueFrom:
                    #secretKeyRef:
                        #name: mongodb-secret
                        #key: mongo-root-username
              #- name: MONGO_INITDB_ROOT_PASSWORD
                #valueFrom:
                    #secretKeyRef:
                        #name: mongodb-secret
                        #key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
    name: mongodb-article
    #namespace: my-app
spec:
    selector:
        app: mongodb-article
    ports:
        - protocol: TCP
          port: 27018
          targetPort: 27017