apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-config
    #namespace: my-app
    labels:
        app: service-config
spec:
    replicas: 1
    selector:
        matchLabels:
            app: service-config
    template:
        metadata:
            labels:
                app: service-config
        spec:
            containers:
            - name: service-config
              image: service-config
              imagePullPolicy: Never
              ports:
              - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
    name: service-config
    #namespace: my-app
spec:
    selector:
        app: service-config
    ports:
        - protocol: TCP
          port: 8888
          targetPort: 8888
