apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-axon
    #namespace: my-app
    labels:
        app: service-axon
spec:
    replicas: 1
    selector:
        matchLabels:
            app: service-axon
    template:
        metadata:
            labels:
                app: service-axon
        spec:
            containers:
            - name: service-axon
              image: axoniq/axonserver:4.5.5
              #imagePullPolicy: Never
              ports:
              - containerPort: 8024
              - containerPort: 8124
---
apiVersion: v1
kind: Service
metadata:
  name: axondb
  labels:
    app: service-axon
spec:
  ports:
  - port: 8124
    name: grpc
    targetPort: 8124
  selector:
    app: service-axon
---
apiVersion: v1
kind: Service
metadata:
  name: axondb-gui
  labels:
    app: service-axon
spec:
  ports:
  - port: 8024
    name: gui
    targetPort: 8024
    nodePort: 30009
  selector:
    app: service-axon
  type: NodePort